language: objective-c
osx_image: xcode11.3

before_install:
   - gem install xcpretty
before_script:
   - set -o pipefail


script:
   - cd class-dump && ls -la
   - mkdir out64
   - sed -i "" -e "s/com.apple.product-type.tool/com.apple.product-type.application/g" class-dump.xcodeproj/project.pbxproj
   - xcodebuild -project class-dump.xcodeproj -configuration Release -sdk iphoneos13.2 -arch arm64 ONLY_ACTIVE_ARCH=NO build TARGET_BUILD_DIR="/User/traivs/build/okanon/class-dump.build/class-dump/out64"
